### ISSUE TITLE
disconnect from admin

### ISSUE THREAD

**Issue by steelwave** [litespeedtech/magento2-LiteSpeed_LiteMage#11] opened 2017-02-21 18:37 UTC
Hi,
I am trying litecache but I am disconnect from admin evry time I am saving or evry few minutes since I installed the extension. It's on magento 2.1.4 and don't happend when the extension is disable.
Thanks.
Laurent

**Comment by litespeedtech** [comment] 2017-02-21 18:52
It's not really LiteMage issue. admin part is not cached.
Please read http://magento.stackexchange.com/questions/101799/magento-2-backend-session-timeout
You need to check magento settings and php.ini.

**Comment by steelwave** [comment] 2017-02-26 19:06
Thanks for your answer but I've got this only with litemage unable.
Do you have an idea?
Thanks.

**Comment by litespeedtech** [comment] 2017-02-27 15:42
Have you checked all the settings based on the previous link? In my test environment, I have admin session set very long, and it won't time out.

**Comment by steelwave** [comment] 2017-02-27 15:58
Thanks for your answer. It's may due to an incorrect litespeed conf? I have litespeed on cpanel. Because as soon as I enable litespeed on litecache module. I can't work on the admin panel as my session closed. Without the module I don't have this problem and a bit with litespeed on.

**Comment by litespeedtech** [comment] 2017-02-27 16:21
from whm litespeed plugin, set cache root according to recommended way.
on LiteSpeed cache configuration, make sure enable public cache is not set, or "No". check public cache is Yes, or you can turn on in .htaccess. https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:common_installation:cpanel-shared
and make sure your license has LiteMage module enabled. 
You can also email info@litespeedtech.com, I can add you to slack chat.

**Comment by Alex-James17** [comment] 2017-07-13 13:35
I am having the same issue with Magento 2.1.7 ever since I enabled the Litespeed_Litemage module. If I disable the module I can use the backend for hours at a time, once the module is enabled I get presented with the login screen every few minutes.

The issue seems to be whenever a cache fail is encountered, for example, I browse to Content > Products, I get login screen. I login and browse to Content > Products, no login screen. I click to edit a product, I get login screen. I login and repeat the above steps, no login screen etc.

This has been driving me mad for 2 weeks now, any ideas? I can provide login details if you need

**Comment by litespeedtech** [comment] 2017-07-26 23:22
Finally this annoying issue got fixed. It was caused by referencing $context which initializer breaks security check. I removed that part. As only it shows additional message of "notifying litespeed server to purge", which is not necessary.
Please try version 2.0.6 and confirm if it fixs for you.

**Comment by Alex-James17** [comment] 2017-07-27 08:47
Seems to have fixed the issue for me, many thanks for getting this resolved so quickly.

**Comment by litespeedtech** [comment] 2017-07-27 13:25
Thanks, I'll close this. Feel bad for steelwave that I was not able to figure out earlier.

**Closed by litespeedtech** 2017-07-27 13:25 UTC

**Comment by biwac** [comment] 2019-10-22 15:14
Hello there,

I encounter the same problem on Magento 2.3.2 with LiteSpeed 5.4.1 and LiteMage 2.1.3

After disableing the module and setting the .htaccess entry LiteMage off, the admin session works as expected.

**Comment by Hedloff** [comment] 2019-10-22 22:21
> Hello there,
> 
> I encounter the same problem on Magento 2.3.2 with LiteSpeed 5.4.1 and LiteMage 2.1.3
> 
> After disableing the module and setting the .htaccess entry LiteMage off, the admin session works as expected.

We also got a customer with the same issue and I have reported this in their slack channel.
You should create a ticket with m2 backend login and they also need user level ssh login so they can check the log and other plugins on your server.

**Comment by an4rei** [comment] 2019-10-26 16:23
If you're using Redis for session storage you won't have this issue.

**Comment by litespeedtech** [comment] 2019-10-28 14:13
I found the cause and fixed in v2.1.4

**Comment by systems-diplomatic** [comment] 2020-05-05 13:13
I'm having this issue with a new installation of LiteSpeed 5.4.7 and LiteMage 2.1.5.
